version: '3.9'

services:
  mkdocs:
    image: thomasve/museit-docs:0.1.1
    container_name: museit-docs
    volumes:
      - ./docs:/site/docs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
