name: Build and Deploy to RKE2

on:
  push:
    branches: [ "master", 'fix/sbom' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: harbor.wizardtower.dev
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.9.2

    - name: Install oras
      uses: oras-project/setup-oras@v1
      with:
        version: 1.2.3

    - name: Build and Push Docker image
      run: |
        docker build . -t harbor.wizardtower.dev/museit/museit-docs:latest
        docker tag harbor.wizardtower.dev/museit/museit-docs:latest harbor.wizardtower.dev/museit/museit-docs:$GITHUB_SHA
        docker push harbor.wizardtower.dev/museit/museit-docs:latest
        docker push harbor.wizardtower.dev/museit/museit-docs:$GITHUB_SHA

    - name: Sign images with Cosign
      env:
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      run: |
        cosign sign \
          --yes \
          --key env://COSIGN_PRIVATE_KEY \
          harbor.wizardtower.dev/museit/museit-docs:latest
        cosign sign \
          --yes \
          --key env://COSIGN_PRIVATE_KEY \
          harbor.wizardtower.dev/museit/museit-docs:$GITHUB_SHA

  deploy:
    runs-on: [ self-hosted, linux, rke2, wizardtower ]
    env:
      KUBECONFIG: /root/.kube/config
    needs: build
    steps:
    - name: Verify Kubeconfig
      run: kubectl get nodes
    - name: Set image in Deployment
      run: |
        kubectl set image deployment/museit-docs museit-docs=harbor.wizardtower.dev/museit/museit-docs:$GITHUB_SHA --namespace=default
        kubectl rollout status deployment/museit-docs --namespace=default
  