name: Build and Deploy to RKE2

on:
  push:
    branches: [ "master", 'fix/sbom' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: harbor.wizardtower.dev
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Create Python SBOM
      run: |
        python -m pip install --upgrade pip
        sudo npm install -g @cyclonedx/cdxgen
        pip install -r requirements.txt
        cdxgen -t python -o sbom.json .

    - name: Install cosign
      run: |
        curl -sSfL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 \
          -o cosign
        chmod +x cosign
        sudo mv cosign /usr/local/bin/

    - name: Install oras
      uses: oras-project/setup-oras@v1
      with:
        version: latest

    - name: Build and Push Docker image
      run: |
        docker build . -t harbor.wizardtower.dev/museit/museit-docs:latest
        docker tag harbor.wizardtower.dev/museit/museit-docs:latest harbor.wizardtower.dev/museit/museit-docs:$GITHUB_SHA
        docker push harbor.wizardtower.dev/museit/museit-docs:latest
        docker push harbor.wizardtower.dev/museit/museit-docs:$GITHUB_SHA

    - name: Push SBOM to Harbor
      run: |
        oras push harbor.wizardtower.dev/museit/museit-docs/sbom:latest \
          --manifest-config sbom-python.json:application/json \
          sbom-python.json:application/json
        oras push harbor.wizardtower.dev/museit/museit-docs/sbom:$GITHUB_SHA \
          --manifest-config sbom-python.json:application/json \
          sbom-python.json:application/json

    - name: Sign SBOM with Cosign
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      run: |
        echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
        cosign sign \
          --key cosign.key \
          harbor.wizardtower.dev/museit/museit-docs/sbom:$GITHUB_SHA

  deploy:
    runs-on: [ self-hosted, linux, rke2, wizardtower ]
    env:
      KUBECONFIG: /root/.kube/config
    needs: build
    steps:
    - name: Verify Kubeconfig
      run: kubectl get nodes
    - name: Set image in Deployment
      run: |
        kubectl set image deployment/museit-docs museit-docs=harbor.wizardtower.dev/museit/museit-docs:$GITHUB_SHA --namespace=default
        kubectl rollout status deployment/museit-docs --namespace=default
  